package tool

// Convert mysql type to go type
var typeConvert = map[string]string{
	"int":                "int64",
	"integer":            "int64",
	"tinyint":            "int64",
	"smallint":           "int64",
	"mediumint":          "int64",
	"bigint":             "int64",
	"int unsigned":       "int64",
	"integer unsigned":   "int64",
	"tinyint unsigned":   "int64",
	"smallint unsigned":  "int64",
	"mediumint unsigned": "int64",
	"bigint unsigned":    "int64",
	"year":               "int64",
	"float":              "float64",
	"double":             "float64",
	"decimal":            "float64",
	"varchar":            "string",
	"char":               "string",
	"tinytext":           "string",
	"mediumtext":         "string",
	"text":               "string",
	"longtext":           "string",
	"enum":               "string",
	"set":                "string",
	"binary":             "[]byte",
	"varbinary":          "[]byte",
	"tinyblob":           "[]byte",
	"blob":               "[]byte",
	"mediumblob":         "[]byte",
	"longblob":           "[]byte",
	"bit":                "[]byte",
	"json":               "[]byte",
	"date":               "time.Time",
	"datetime":           "time.Time",
	"timestamp":          "time.Time",
	"time":               "time.Time",
}
